# Generated by Django 2.2 on 2021-06-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=1)),
                ('number_of_visit', models.IntegerField()),
                ('picture_list', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
                ('picture_detail', models.ImageField(upload_to='pictures/%Y/%m/%d/')),
            ],
        ),
    ]
