# Generated by Django 2.2 on 2021-06-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief',
            field=models.TextField(default='breif'),
            preserve_default=False,
        ),
    ]
