# Generated by Django 2.2 on 2021-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
