# Generated by Django 2.2 on 2021-07-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_bridge_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['rate']},
        ),
    ]
