# Generated by Django 2.2 on 2021-07-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20210701_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-rate']},
        ),
    ]
