# Generated by Django 2.2 on 2021-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210702_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
